---

- hosts: all
  become: true
  tasks:

  - name: install httpd & php support for apache
    dnf:
      name:
        - httpd
        - php
      state: present
      update_cache: yes
    when: ansible_distribution in ["Rocky", "CentOS"]

  - name: install apache2 & php  package
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: present
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

