- name: install httpd & php support for apache 
  tags: apache,httpd,centos,rocky
  dnf:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start httpd
  tags: apache,httpd,centos
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change -email adress for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.com
  when: ansible_distribution in ["Rocky", "CentOS"]
  notify: restart_apache

- name: copy defula html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
