- name: install httpd & php support for apache (Rocky or CentOS)
  tags: apache,httpd,centos,rocky
  dnf:
    name:
      - httpd
      - php
    state: present
  when: ansible_distribution in ["Rocky", "CentOS"]

- name: start httpd (Rocky or CentOS)
  tags: apache,httpd,centos
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution in ["Rocky", "CentOS"]

- name: install apache2 & php  package (Ubuntu)
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: present
  when: ansible_distribution == "Ubuntu"

- name: change -email adress for admin
  tags: apache,centos,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution in ["Rocky", "CentOS"]
  register: httpd

- name: restart httpd (CentOS, Rocky)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy defula html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
